const $=id=>document.getElementById(id);const mobileMenuBtn=$('mobileMenuBtn'),mobileNav=$('mobileNav'),searchBtn=$('searchBtn'),searchOverlay=$('searchOverlay'),closeSearch=$('closeSearch'),searchInput=$('searchInput'),cartBtn=$('cartBtn'),cartDrawer=$('cartDrawer'),cartOverlay=$('cartOverlay'),closeCart=$('closeCart'),cartItemsContainer=$('cartItems'),cartCount=$('cartCount'),cartTotal=$('cartTotal'),toast=$('toast'),productModal=$('productModal'),modalClose=$('modalClose'),modalImage=$('modalImage'),modalName=$('modalName'),modalCategory=$('modalCategory'),modalPrice=$('modalPrice'),modalAdd=document.querySelector('.modal-add'),newsletterForm=$('newsletterForm'),newsletterMessage=$('newsletterMessage');let cart=[],currentModalProduct=null,toastTimer;
function formatPrice(price){return new Intl.NumberFormat('en-IN',{style:'currency',currency:'INR',maximumFractionDigits:0}).format(price)}
function showToast(message){toast.querySelector('span').textContent=message;toast.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>toast.classList.remove('show'),2500)}
mobileMenuBtn.addEventListener('click',()=>{mobileNav.classList.toggle('active');const icon=mobileMenuBtn.querySelector('i');icon.classList.toggle('fa-bars');icon.classList.toggle('fa-xmark')});document.querySelectorAll('.mobile-nav a').forEach(l=>l.addEventListener('click',()=>{mobileNav.classList.remove('active');const i=mobileMenuBtn.querySelector('i');i.classList.add('fa-bars');i.classList.remove('fa-xmark')}));
searchBtn.addEventListener('click',()=>{searchOverlay.classList.add('active');setTimeout(()=>searchInput.focus(),300)});closeSearch.addEventListener('click',()=>searchOverlay.classList.remove('active'));searchOverlay.addEventListener('click',e=>{if(e.target===searchOverlay)searchOverlay.classList.remove('active')});document.addEventListener('keydown',e=>{if(e.key==='Escape'){searchOverlay.classList.remove('active');productModal.classList.remove('active')}});
searchInput.addEventListener('input',()=>{const term=searchInput.value.toLowerCase().trim();document.querySelectorAll('.product-card').forEach(p=>{const match=p.dataset.name.toLowerCase().includes(term)||p.dataset.category.toLowerCase().includes(term);p.classList.toggle('hidden',!match)})});
const filterButtons=document.querySelectorAll('.filter-btn'),products=document.querySelectorAll('.product-card');filterButtons.forEach(b=>b.addEventListener('click',()=>{const f=b.dataset.filter;filterButtons.forEach(x=>x.classList.remove('active'));b.classList.add('active');products.forEach(p=>p.classList.toggle('hidden',f!=='all'&&p.dataset.category!==f))}));
document.querySelectorAll('.category-card').forEach(c=>c.addEventListener('click',()=>{const b=document.querySelector(`.filter-btn[data-filter="${c.dataset.category}"]`);if(b)b.click();$('products').scrollIntoView({behavior:'smooth'})}));
document.querySelectorAll('.add-cart').forEach(b=>b.addEventListener('click',e=>{e.stopPropagation();addToCart(b.closest('.product-card'))}));
function addToCart(product){if(!product)return;const d={id:product.dataset.name,name:product.dataset.name,category:product.dataset.category,price:Number(product.dataset.price)};const existing=cart.find(x=>x.id===d.id);existing?existing.quantity++:(d.quantity=1,cart.push(d));updateCart();showToast(`${d.name} added to your bag`)}
function updateCart(){cartCount.textContent=cart.reduce((s,x)=>s+x.quantity,0);cartTotal.textContent=formatPrice(cart.reduce((s,x)=>s+x.price*x.quantity,0));if(!cart.length){cartItemsContainer.innerHTML='<div class="empty-cart"><i class="fa-solid fa-bag-shopping"></i><h3>Your bag is empty</h3><p>Add something beautiful to get started.</p><button class="btn btn-primary" id="continueShopping">Continue Shopping</button></div>';document.getElementById('continueShopping').addEventListener('click',closeCartDrawer);return}cartItemsContainer.innerHTML=cart.map((x,i)=>`<div class="cart-item"><div class="cart-item-image ${getProductImageClass(x.category)}"></div><div class="cart-item-info"><h4>${x.name}</h4><p>${formatPrice(x.price)} × ${x.quantity}</p></div><button class="remove-item" data-index="${i}"><i class="fa-solid fa-trash"></i></button></div>`).join('');document.querySelectorAll('.remove-item').forEach(b=>b.addEventListener('click',()=>{cart.splice(Number(b.dataset.index),1);updateCart()}))}
function getProductImageClass(category){return category==='Sarees'?'product-one':category==='Kurtis'?'product-two':category==='Dresses'?'product-three':'product-four'}
cartBtn.addEventListener('click',openCartDrawer);closeCart.addEventListener('click',closeCartDrawer);cartOverlay.addEventListener('click',closeCartDrawer);function openCartDrawer(){cartDrawer.classList.add('active');cartOverlay.classList.add('active');document.body.style.overflow='hidden'}function closeCartDrawer(){cartDrawer.classList.remove('active');cartOverlay.classList.remove('active');document.body.style.overflow=''}
document.querySelectorAll('.wishlist').forEach(b=>b.addEventListener('click',e=>{e.stopPropagation();b.classList.toggle('active');const i=b.querySelector('i');i.classList.toggle('fa-regular');i.classList.toggle('fa-solid');showToast(b.classList.contains('active')?'Added to wishlist':'Removed from wishlist')}));
document.querySelectorAll('.quick-view').forEach(b=>b.addEventListener('click',e=>{e.stopPropagation();openProductModal(b.closest('.product-card'))}));function openProductModal(product){currentModalProduct=product;modalName.textContent=product.dataset.name;modalCategory.textContent=product.dataset.category.toUpperCase();modalPrice.textContent=formatPrice(Number(product.dataset.price));modalImage.className='modal-image '+getProductImageClass(product.dataset.category);productModal.classList.add('active');document.body.style.overflow='hidden'}function closeProductModal(){productModal.classList.remove('active');document.body.style.overflow=''}modalClose.addEventListener('click',closeProductModal);productModal.addEventListener('click',e=>{if(e.target===productModal)closeProductModal()});modalAdd.addEventListener('click',()=>{if(currentModalProduct){addToCart(currentModalProduct);closeProductModal();openCartDrawer()}});
newsletterForm.addEventListener('submit',e=>{e.preventDefault();if(!$('email').value.trim())return;newsletterMessage.textContent="Thank you! You're now part of Threads2Trendz.";newsletterMessage.style.color='#6d4c41';newsletterForm.reset();showToast('Successfully subscribed')});document.querySelector('.checkout-btn').addEventListener('click',()=>showToast(cart.length?'Checkout integration can be connected here':'Your bag is empty'));
window.addEventListener('scroll',()=>{document.getElementById('header').style.boxShadow=scrollY>100?'0 5px 25px rgba(0,0,0,.06)':'none'});
const revealObserver=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){e.target.style.opacity='1';e.target.style.transform='translateY(0)';revealObserver.unobserve(e.target)}}),{threshold:.08});document.querySelectorAll('.section,.product-card,.category-card,.feature').forEach(el=>{el.style.opacity='0';el.style.transform='translateY(25px)';el.style.transition='opacity .7s ease, transform .7s ease';revealObserver.observe(el)});updateCart();